spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/Mulcamp

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/arx?serverTimezone=Asia/Seoul
    username: root
    password: choi7687
    driver-class-name: com.mysql.cj.jdbc.Driver